load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pool",
    srcs = [
        "pool.cc",
    ],
    hdrs = [
        "pool.h",
    ],
    deps = [
    ],
)

cpplint()
