load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "txpool",
    srcs = [
        "txpool.cc",
    ],
    hdrs = [
        "txpool.h",
        "txpool_construct.h",
    ],
    deps = [
    ],
)

cpplint()
